### ISSUE TITLE
big blob (INSERT INTO t VALUES (zeroblob(1024 * 1024 - 1),...) overflow page error

### ISSUE THREAD

**Issue by pereman2** [tursodatabase/turso#406]
```bash
Limbo v0.0.5
Enter ".help" for usage hints.
limbo> CREATE TABLE t(x1, x2, x3, x4);
limbo> INSERT INTO t VALUES (zeroblob(1024 * 1024 - 1), zeroblob(1024 * 1024 - 2), zeroblob(1024 * 1024 - 3), zeroblob(1024 * 1024 - 4));
thread 'main' panicked at core/io/linux.rs:90:18:
submission queue is full: PushError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    257149 IOT instruction (core dumped)  limbo a1.db
```
It seems like allocation of overflow pages can cause overflow of submission queue.

**Comment by penberg** [comment]
The push error issue has been fixed, but the saga continues at #1625:

```
limbo> CREATE TABLE t(x1, x2, x3, x4);
limbo> INSERT INTO t VALUES (zeroblob(1024 * 1024 - 1), zeroblob(1024 * 1024 - 2), zeroblob(1024 * 1024 - 3), zeroblob(1024 * 1024 - 4));
thread 'main' panicked at core/storage/pager.rs:535:41:
called `Result::unwrap()` on an `Err` value: CacheFull
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
