### ISSUE TITLE
`sqlite_version()` SQL function panics

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso#560]
```
Limbo v0.0.10
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database
limbo> SELECT sqlite_version();
thread 'main' panicked at core/vdbe/mod.rs:2750:72:
index out of bounds: the len is 3 but the index is 3
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_bounds_check
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:276:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /Users/penberg/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:301:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /Users/penberg/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:16:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /Users/penberg/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3323:9
   6: limbo_core::vdbe::Program::step
             at ./core/vdbe/mod.rs:2750:72
   7: limbo_core::Statement::step
             at ./core/lib.rs:378:22
   8: limbo_core::Rows::next_row
             at ./core/lib.rs:425:9
   9: limbo::app::Limbo::query
             at ./cli/app.rs:500:27
  10: limbo::app::Limbo::handle_input_line::{{closure}}
             at ./cli/app.rs:385:37
  11: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /Users/penberg/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:810:29
  12: core::iter::adapters::filter::filter_fold::{{closure}}
             at /Users/penberg/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/filter.rs:79:44
  13: core::iter::adapters::map::map_fold::{{closure}}
             at /Users/penberg/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:88:21
  14: core::iter::traits::iterator::Iterator::fold
             at /Users/penberg/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2584:21
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /Users/penberg/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:128:9
  16: <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::fold
             at /Users/penberg/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/filter.rs:159:9
  17: core::iter::traits::iterator::Iterator::for_each
             at /Users/penberg/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:813:9
  18: limbo::app::Limbo::handle_input_line
             at ./cli/app.rs:378:13
  19: limbo::main
             at ./cli/main.rs:20:31
  20: core::ops::function::FnOnce::call_once
             at /Users/penberg/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by el-yawd** [comment]
The error is happening here:
```rust
                Insn::Copy {
                    src_reg,
                    dst_reg,
                    amount,
                } => {
                    for i in 0..=*amount {
                        state.registers[*dst_reg + i] = state.registers[*src_reg + i].clone();
                    }
                    state.pc += 1;
                }
```
removing  `=` in the range resolves it, but of course, breaks everything. Probably the error is in the creation of `Insn` vector.

EDIT: I founded the error! It is in the expression translation. I gonna add a test for this and open a PR.

**Comment by penberg** [comment]
Fixed by https://github.com/tursodatabase/limbo/pull/561
